services:
  product-service:
    container_name: product
    image: ${DOCKER_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/jfs"
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
      INFERENCE_BASE_URL: "http://inference:8000"
      # ONLY keep this if your app is configured to run on 5050 in-container
      SERVER_PORT: "5050"
    ports:
      - "${HOST_PORT}:5050"
    depends_on:
      - db
      - inference
    networks:
      - amigos

  inference:
    container_name: inference
    image: my-mlops-demo-inference
    # or your built image name
    expose:
      - "8000"
    networks:
      - amigos

  db:
    container_name: jfs-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: jfs
    ports:
      - "5333:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - amigos

networks:
  amigos:
    driver: bridge

volumes:
  db:
